language: python

sudo: required

python:
  - "3.7"

services:
  - docker

before_script:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
